commerce_pricelist.price_list_type.*:
  type: config_entity
  label: 'Price list type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

commerce_pricelist.price_list_item_type.*:
  type: commerce_config_entity_bundle
  label: 'Price list item type config'
  mapping:
    purchasableEntityType:
      type: string
      label: 'Purchasable entity type ID.'
    priceListType:
      type: string
      label: 'Pricelist entity type ID.'
